#22 - aws tests execution

diff --git a/.github/workflows/performance.yml b/.github/workflows/performance.yml
--- a/.github/workflows/performance.yml
+++ b/.github/workflows/performance.yml
@@ -1,5 +1,18 @@
 name: PerformanceTests
 
+env:
+  SERVER_ADDRESS: ${{ inputs.server_private_address || '172.31.38.198' }}
+  LISTEN_ADDRESS: 127.0.0.1
+  SERVER_PUBLIC_ADDRESS: ${{ inputs.server_public_address || '35.163.142.7' }}
+  CLIENT_LISTEN_ADDRESS: ${{ inputs.client_listen_address || '172.31.21.30' }}
+  SERVER_WAIT_TIMEOUT: ${{ inputs.server_wait_timeout || 150 }}
+  CONNECT_DELAY_MS: ${{ inputs.connect_delay_ms || 100 }}
+  CONNECT_DELAY_DEVICE: ${{ inputs.connect_delay_device || 'eth0' }}
+  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+  AWS_INSTANCE_ID: ${{ secrets.AWS_INSTANCE_ID }}
+
 on:
   schedule:
     - cron: '1 1 * * *'
@@ -17,52 +30,95 @@ on:
         default: 172.31.38.198
         required: true
       client_listen_address:
-        description: 'address for the client to listen on'
+        description: 'private address for the client to listen on'
         type: string
-        default: 192.168.1.21
+        default: 172.31.21.30
         required: true
       server_wait_timeout:
         description: 'Server global timeout for tests'
         type: integer
-        default: 45
+        default: 150
         required: false
-      connection_delay_ms:
+      connect_delay_ms:
         description: 'connection delay in milliseconds set on the server'
         type: integer
         default: 0
         required: true
-      connection_delay_device:
+      connect_delay_device:
         description: 'serverside network device to set delay on'
         type: string
         default: eth0
         required: true
-      remove_qpep_image:
-        description: 'remove qpep image at end of run'
+      keep_aws_running:
+        description: 'keeps aws vm running for subsequent runs'
         type: boolean
         default: false
         required: true
 
-run-name: Performance Testing [${{ github.event_name }}] - ${{ inputs.server_public_address }}/${{ inputs.connection_delay_ms }}ms delay
+run-name: Performance Testing [${{ github.event_name }}][${{ github.head_ref || github.ref_name }}] - ${{ inputs.server_public_address || '35.163.142.7' }}/${{ inputs.connect_delay_ms || '500' }}ms delay
 
 jobs:
+  launch-aws-vm:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install AWS cli
+        id: install-aws-cli
+        uses: unfor19/install-aws-cli-action@master
+        with:
+          version: "2"
+
+      - run: |
+          aws --version
+          # run the instance
+          aws ec2 start-instances --instance-ids ${{ secrets.AWS_INSTANCE_ID }}
+        shell: bash
+
+      - run: |
+          # assure that the instance is stopped on error
+          aws ec2 stop-instances --instance-ids ${{ secrets.AWS_INSTANCE_ID }}
+        shell: bash
+        if: ${{ failure() && ! inputs.keep_aws_running }}
+
+  stop-aws-vm:
+    runs-on: ubuntu-latest
+    needs: run-client
+    if: ${{ always() && ! inputs.keep_aws_running }}
+    steps:
+      - name: Install AWS cli
+        id: install-aws-cli
+        uses: unfor19/install-aws-cli-action@master
+        with:
+          version: "2"
+
+      - run: |
+          # assure that the instance is stopped even on error
+          aws ec2 stop-instances --instance-ids ${{ secrets.AWS_INSTANCE_ID }}
+        shell: bash
+
   run-client:
     runs-on: vm-client
-    env:
-      REMOTE_GATEWAY: ${{ inputs.server_public_address }}
-      LISTEN_ADDRESS: ${{ inputs.client_listen_address }}
+    needs: launch-aws-vm
     strategy:
       matrix:
-        download_size: [ 10, 100 ]
-        connections_number: [ 1, 4 ]
+        download_size: [ 100, 10, 1 ]
+        connections_number: [ 4, 1 ]
     steps:
       - uses: actions/checkout@v3
         with:
           clean: true
+          ref: ${{ github.head_ref || github.ref_name }}
 
       - name: Set up Go
         uses: actions/setup-go@v3
         with:
           go-version: 1.18.10
+
+      - name: Set up MinGW
+        uses: egor-tensin/setup-mingw@v2
+        with:
+          platform: x64
+          static: false
+          version: 8.1.0
 
       - name: Prepare
         shell: powershell
@@ -70,8 +126,8 @@ jobs:
           New-Item -Path . -Name "build" -ItemType "directory" -Force
           New-Item -Path . -Name "build/config" -ItemType "directory" -Force
           $config = Get-Content -Path ./docker/client-env/qpep.yml.tpl
-          $config = $config.replace('<QPEP_GATEWAY>',$env:REMOTE_GATEWAY)
-          $config = $config.replace('<QPEP_ADDRESS>',$env:LISTEN_ADDRESS)
+          $config = $config.replace('<QPEP_GATEWAY>',$env:SERVER_PUBLIC_ADDRESS)
+          $config = $config.replace('<QPEP_ADDRESS>',$env:CLIENT_LISTEN_ADDRESS)
           $config > ./build/config/qpep.yml
           Copy-Item "./windivert/x64/*" -Destination "./build"
 
@@ -89,21 +145,23 @@ jobs:
           go build -v -o build/qpep.exe
 
       - name: Run Client
-        shell: cmd
+        shell: powershell
         run: |
           cd build/
-          cmd /c "START /b qpep.exe -c"
+          Start-Process qpep.exe -Wait -ArgumentList ("/client /service install")
+          Start-Process qpep.exe -Wait -ArgumentList ("/client /service start")
+          Start-Sleep -Seconds 5
 
       - name: Wait Server
         shell: powershell
         run: |
           $Stoploop = $false
-          [ int ]$Retrycount = "20"
+          [ int ]$Retrycount = "60"
 
            do {
             try {
               Write-Host "Echoing server..."
-              Invoke-WebRequest -Uri "http://${{ inputs.server_public_address }}:444/api/v1/server/echo" -UseBasicParsing -TimeoutSec 1
+              Invoke-WebRequest -Uri "http://${{ env.SERVER_PUBLIC_ADDRESS }}:444/api/v1/server/status" -UseBasicParsing -TimeoutSec 2
               Write-Host "Job completed"
               $Stoploop = $true
             }
@@ -125,17 +183,25 @@ jobs:
           cd docker/speedtests/
           go test speed_test.go -v -c -o speedtests.test
 
-          .\speedtests.test -target_url http://${{ inputs.server_public_address }}:8080/target_${{ matrix.download_size }}M.dat ^
+          .\speedtests.test -target_url http://${{ env.SERVER_PUBLIC_ADDRESS }}:8080/target_${{ matrix.download_size }}M.dat ^
              -expect_mb ${{ matrix.download_size }} -connections_num ${{ matrix.connections_number }} ^
              -test.v -test.timeout 5m > speedtests.out
 
-          go run utils/plotter.go output.csv "Client speed test [Delay:${{ inputs.connection_delay_ms }}ms][TargetSize:${{ matrix.download_size }}M][Connections:${{ matrix.connections_number }}]"
+          go run utils/plotter.go output.csv "Client speed test [Delay:${{ env.CONNECT_DELAY_MS }}ms][TargetSize:${{ matrix.download_size }}M][Connections:${{ matrix.connections_number }}]"
 
       - name: Stop Client
         if: always()
         shell: powershell
         run: |
-          Get-Process qpep | Stop-Process
+          cd build/
+          Start-Process qpep.exe -Wait -ArgumentList ("/client /service stop")
+          Start-Process qpep.exe -Wait -ArgumentList ("/client /service uninstall")
+          Start-Sleep -Seconds 5
+          try {
+            Get-Process qpep | Stop-Process
+          }
+          catch
+          { }
 
       - name: Reset Proxy
         if: always()
@@ -144,13 +210,18 @@ jobs:
 
       - uses: actions/upload-artifact@v3
         with:
-          name: client_${{ inputs.connection_delay_ms }}ms_${{ matrix.download_size }}MB_${{ matrix.connections_number }}conn
+          name: client_${{ env.CONNECT_DELAY_MS }}ms_${{ matrix.download_size }}MB_${{ matrix.connections_number }}conn
           path: |
             ${{ github.workspace }}/docker/speedtests/output.csv
             ${{ github.workspace }}/docker/speedtests/speedtests.out
             ${{ github.workspace }}/docker/speedtests/speedtests.log
-            ${{ github.workspace }}/docker/speedtests/data.png
             ${{ github.workspace }}/build/*.log
+
+      - uses: actions/upload-artifact@v3
+        with:
+          name: graph_client_${{ env.CONNECT_DELAY_MS }}ms_${{ matrix.download_size }}MB_${{ matrix.connections_number }}conn
+          path: |
+            ${{ github.workspace }}/docker/speedtests/data.png
 
       - name: Auto-cancel workflow on error
         if: failure()
@@ -158,9 +229,7 @@ jobs:
 
   run-server:
     runs-on: vm-server
-    env:
-      SERVER_ADDRESS: ${{ inputs.server_private_address }}
-      LISTEN_ADDRESS: 127.0.0.1
+    needs: launch-aws-vm
     steps:
       - name: Pre-Cleanup
         run: |
@@ -169,6 +238,7 @@ jobs:
       - uses: actions/checkout@v3
         with:
           clean: true
+          ref: ${{ github.head_ref || github.ref_name }}
 
       - name: Set up Go
         uses: actions/setup-go@v3
@@ -176,11 +246,13 @@ jobs:
           go-version: 1.18.10
 
       - name: Build Server
+        env:
+          QPEP_BRANCH: ${{ github.head_ref || github.ref_name }}
         run: |
           docker version
           cd docker/
           pushd build-linux/
-          docker build -t project-faster/qpep_server .
+          docker build --no-cache -t project-faster/qpep_server .
 
       - name: Run data server
         run: |
@@ -200,19 +272,19 @@ jobs:
           sudo bash ${{ github.workspace }}/.github/workflows/set_delay_port.sh -d
 
       - name: Set connection delay
-        if: inputs.connection_delay_device > 0
+        if: inputs.connect_delay_device > 0
         run: |
-          sudo bash ${{ github.workspace }}/.github/workflows/set_delay_port.sh "${{ inputs.connection_delay_ms }}" "${{ inputs.connection_delay_device }}"
+          sudo bash ${{ github.workspace }}/.github/workflows/set_delay_port.sh "${{ env.CONNECT_DELAY_MS }}" "${{ env.CONNECT_DELAY_DEVICE }}"
 
       - name: Wait Tests
         timeout-minutes: 60 # max allowed timeouts
         run: |
           # initial wait for server setup
           sleep 60
-          
+
           echo [Starting wait for tests execution...]
           CONN_NUM=1
-          RETRIES=${{ inputs.server_wait_timeout }}
+          RETRIES=${{ env.SERVER_WAIT_TIMEOUT }}
           while ! (( RETRIES <= 0 ));
           do
             CONN_NUM=$(curl -s -XGET -H 'Accept:application/json' http://127.0.0.1:444/api/v1/server/echo | jq .total_connections || true)
@@ -221,7 +293,7 @@ jobs:
               (( RETRIES -= 1 )) || true
               echo "Remaining $RETRIES retries"
             else
-              (( RETRIES=${{ inputs.server_wait_timeout }} )) || true
+              (( RETRIES=${{ env.SERVER_WAIT_TIMEOUT }} )) || true
               echo "Remaining $RETRIES retries"
             fi
             sleep 1
@@ -243,15 +315,20 @@ jobs:
       - name: Generate results
         run: |
           cd docker/speedtests/
-          go run utils/plotter.go ${{ github.workspace }}/docker/server-data-env/output/data.csv "Server speed test [Delay:${{ inputs.connection_delay_ms }}ms]" "perf-dw-speed"
+          go run utils/plotter.go ${{ github.workspace }}/docker/server-data-env/output/data.csv "Server speed test [Delay:${{ env.CONNECT_DELAY_MS }}ms]" "perf-dw-speed"
 
       - uses: actions/upload-artifact@v3
         with:
-          name: server_${{ inputs.connection_delay_ms }}ms
+          name: server_${{ env.CONNECT_DELAY_MS }}ms
           path: |
             ${{ github.workspace }}/docker/server-data-env/output/data.csv
-            ${{ github.workspace }}/docker/speedtests/data.png
             ${{ github.workspace }}/build/*.log
+
+      - uses: actions/upload-artifact@v3
+        with:
+          name: graph_server_${{ env.CONNECT_DELAY_MS }}ms
+          path: |
+            ${{ github.workspace }}/docker/speedtests/data.png
 
       - name: Cleanup
         if: always()
@@ -260,7 +337,7 @@ jobs:
           sudo rm -rf docker/server-data-env/output/* || true
 
       - name: Remove server image
-        if: ${{ inputs.remove_qpep_image }}
+        if: failure()
         run: |
           docker image rm project-faster/qpep_server || true
 
